# Dependencies
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "strikethrough", "superscript", "with_toc_data"]

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
# relative_permalinks: true

# Setup
title:               'Tu Hoang'
tagline:             'parttime Ruby dev, fulltime Bun Rieu maniac'
description:         'parttime Ruby dev, fulltime Bun Rieu maniac'
url:                 http://nogias.com
baseurl:             /
paginate:            5

# About/contact
author:
  name:              Tu Hoang
  url:               https://twitter.com/rebyn
  email:             saidrebyn@gmail.com

# Custom vars
version:             1.0.0
gems:
  - jekyll-feed
